config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'omni_auth'
    
  }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end
  root 'home#index', as: 'home'
  get 'home/index'



  resources :catagory, only: [:index] do
    resources :books, only: [:index] do
      member do
        get :read
      end
      resources :comments
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	has_many :book_catagories
	has_many :catagories, through: :book_catagories
	has_many :comments

	has_one_attached  :thumbnail
	has_one_attached  :pdf
end

app/models/book_catagory.rb
class BookCatagory < ApplicationRecord
  belongs_to :book
  belongs_to :catagory
end

app/models/catagory.rb
class Catagory < ApplicationRecord

	has_many :book_catagories
	has_many :book, through: :book_catagories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
     # user.provider = auth.provider
      #user.uid = auth.uid
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_book_catagories

	def set_book_catagories
	    @b_catagories =  Catagory.all.order("created_at DESC")
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	

	def index
		@catagory = Catagory.find(params[:catagory_id])
  		@books = @catagory.book.order(:title)
	end
    before_action :authenticate_user!
	def read

		@catagory = Catagory.find(params[:catagory_id])
		@books = @catagory.book.find(params[:id])
		
	end

	#def create
		#@book = Book.new()
		#if @book.save
		#	redirect_to @post
		#else
			#render new
		#end
		
	#end

	#private

	#def post_params
	#	params.require(:book).permit(:title, :cotent)
	#end
end

app/controllers/catagory_controller.rb
class CatagoryController < ApplicationController
	def _nav
		@catagories = Catagory.all
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		redirect_to read_catagory_book_path(@catagory.id,@books.id)
	end
	def create
		@catagory = Catagory.find(params[:catagory_id])
		@books = @catagory.book.find(params[:book_id])
		@comment = @books.comments.create(comment_params)
		redirect_to read_catagory_book_path(@catagory.id,@books.id)
	end
	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@catagories =  Catagory.all.order("created_at DESC")
  	
  end
end

app/controllers/omni_auth_controller.rb
class OmniAuthController < Devise::OmniauthCallbacksController

	def google_oauth2
		
		@user = User.create_from_provider_data(request.env['omniauth.auth'])
			if @user.persisted?
				sign_in_and_redirect @user
			else
				flash[:error] = "There was a problem in signing you in through Google. Please register or sign in later."
				redirect_to new_user_registration_url
			end
			
		end
	
	def failure
		flash[:error] = "There was a problem in signing you in. Please register or sign in later."
		redirect_to new_user_registration_url
	end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(_resource)
    home_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/catagory_helper.rb
module CatagoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omni_auth_helper.rb
module OmniAuthHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="#"><%= image_tag('logo.png', {:style => "width:100px;"}) %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% unless @b_catagories.nil? %>
                  <% @b_catagories.each do |catagory| %>
                    <div class="dropdown-item btn">
                    <%= link_to catagory_books_path(catagory)  do %>
                      <%= catagory.title  %>
                    <% end %> 
                    </div>  
                  <% end %>
            <% end %>
          </div>

        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if current_user %>
                <div class="btn btn-outline-light my-2 my-sm-0" ><%= link_to "Logout", destroy_user_session_path, method: :delete %></div>
        <% else %>
          <div class="btn btn-outline-light my-2 my-sm-0">
            <%= link_to "Login", new_user_session_path %>
          </div>
          <!--<button class="btn btn-secondary my-2 my-sm-0" >-->
        <% end %>
      </form>
    </div>
  </nav>
            
         
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>